audio.h was moved to f1.h
gaintoolui.h was moved to f2.h
genfunct.h was moved to f3.h
phonetone.h was moved to f4.h
play.h was moved to f5.h
ptcreate.h was moved to f6.h
ptmain.h was moved to f7.h
ptvx.h was moved to f8.h
ptxv.h was moved to f9.h
